# Generated by Django 5.2.3 on 2025-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articleitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('main_page', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Shop Item',
            },
        ),
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_lname', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
