# Generated by Django 5.2.3 on 2025-07-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleitem',
            options={'verbose_name': 'Article Item'},
        ),
        migrations.AlterModelOptions(
            name='contactos',
            options={'verbose_name': 'Contact Us'},
        ),
        migrations.RenameField(
            model_name='articleitem',
            old_name='main_page',
            new_name='mainTF',
        ),
    ]
