# Generated by Django 5.2.3 on 2025-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articleitem_options_alter_contactos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='number',
        ),
        migrations.RemoveField(
            model_name='contactos',
            name='title',
        ),
        migrations.AddField(
            model_name='contactos',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contactos',
            name='Message',
            field=models.TextField(default=''),
        ),
    ]
